version: '3.0'


services:
  webserver:
    container_name: framework-web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80


  app:
    container_name: framework-app
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - ./.env
    volumes:
      - .:/app

  db:
    container_name: framework-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    volumes:
      - ./db-folder:/var/lib/postgresql/data
