version: '3.0'


services:
  webserver:
    container_name: framework-web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80


  app:
    container_name: framework-app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
